# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_search_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt
from urllib.request import urlopen
import requests
from PyQt5.QtGui import QPixmap
from PIL import Image
import io

API_KEY = 'AIzaSyD001rDK_gE2qkZo8mg5jDS8hSc04FY2ug'
SEARCH_ENGINE_ID = '001089964355375223555:eoos11d3zqw'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setAccessibleName("")
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(770, 20, 131, 51))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons8-search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.retranslateUi(MainWindow))
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 100, 1241, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1239, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_1.setText("")
        self.img_1.setObjectName("img_1")
        self.verticalLayout.addWidget(self.img_1)
        self.img_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_2.setText("")
        self.img_2.setObjectName("img_2")
        self.verticalLayout.addWidget(self.img_2)
        self.img_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_3.setText("")
        self.img_3.setObjectName("img_3")
        self.verticalLayout.addWidget(self.img_3)
        self.img_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_4.setText("")
        self.img_4.setObjectName("img_4")
        self.verticalLayout.addWidget(self.img_4)
        self.img_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.img_5.setText("")
        self.img_5.setObjectName("img_5")
        self.verticalLayout.addWidget(self.img_5)
        # self.img_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.img_6.setText("")
        # self.img_6.setObjectName("img_6")
        # self.verticalLayout.addWidget(self.img_6)
        # self.img_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.img_7.setText("")
        # self.img_7.setObjectName("img_7")
        # self.verticalLayout.addWidget(self.img_7)
        # self.img_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.img_8.setText("")
        # self.img_8.setObjectName("img_8")
        # self.verticalLayout.addWidget(self.img_8)
        # self.img_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.img_9.setText("")
        # self.img_9.setObjectName("img_9")
        # self.verticalLayout.addWidget(self.img_9)
        # self.img_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        # self.img_10.setText("")
        # self.img_10.setObjectName("img_10")
        # self.verticalLayout.addWidget(self.img_10)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setWindowTitle("Image Search Engine")
        MainWindow.setWindowIcon(QtGui.QIcon(r'assets\icon.png'))
        self.pushButton.setText("Search")

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        global query
        _translate = QtCore.QCoreApplication.translate

        page = 1
        query = self.lineEdit.text()
        self.lineEdit.setText('')
        start = (page - 1) * 10 + 1
        url = f"https://www.googleapis.com/customsearch/v1?key={API_KEY}&cx={SEARCH_ENGINE_ID}&q={query}&start={start}&searchType=IMAGE"
        data = requests.get(url).json()
        print(data)
        search_items = data.get('items')
        print(search_items)
        img_width = 1190
        z = 0
        while True:
            try:
                im = Image.open(io.BytesIO(urlopen(search_items[z].get('link'), timeout=5).read()))
                break
            except:
                z=(z+1)%11
        try:
            im.save(r'cache/d1.jpg')
            self.img_1.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(img_width))
        except OSError:
            im.save(r'cache/d1.png')
            self.img_1.setPixmap(QPixmap(r'cache/d1.png').scaledToWidth(img_width))

        z = (z+1) % 11
        while True:
            try:
                im = Image.open(io.BytesIO(urlopen(search_items[z].get('link'), timeout=5).read()))
                break
            except:
                z = (z + 1) % 11
        try:
            im.save(r'cache/d1.jpg')
            self.img_2.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(img_width))
        except OSError:
            im.save(r'cache/d1.png')
            self.img_2.setPixmap(QPixmap(r'cache/d1.png').scaledToWidth(img_width))
        z = (z+1) % 11
        while True:
            try:
                im = Image.open(io.BytesIO(urlopen(search_items[z].get('link'), timeout=5).read()))
                break
            except:
                z = (z + 1) % 11
        try:
            im.save(r'cache/d1.jpg')
            self.img_3.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(img_width))
        except OSError:
            im.save(r'cache/d1.png')
            self.img_3.setPixmap(QPixmap(r'cache/d1.png').scaledToWidth(img_width))
        z =( z+1) % 11
        while True:
            try:
                im = Image.open(io.BytesIO(urlopen(search_items[z].get('link'), timeout=5).read()))
                break
            except:
                z = (z + 1) % 11
        try:
            im.save(r'cache/d1.jpg')
            self.img_4.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(img_width))
        except OSError:
            im.save(r'cache/d1.png')
            self.img_4.setPixmap(QPixmap(r'cache/d1.png').scaledToWidth(img_width))
        z=(z+1)%11
        while True:
            try:
                im = Image.open(io.BytesIO(urlopen(search_items[z].get('link'), timeout=5).read()))
                break
            except:
                z = (z + 1) % 11
        try:
            im.save(r'cache/d1.jpg')
            self.img_5.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(img_width))
        except OSError:
            im.save(r'cache/d1.png')
            self.img_5.setPixmap(QPixmap(r'cache/d1.png').scaledToWidth(img_width))
        # z += 1
        # im = Image.open(io.BytesIO(urlopen(search_items[z].get('link')).read()))
        # im.save(r'cache/d1.jpg')
        # self.img_6.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(1200))
        # z += 1
        # im = Image.open(io.BytesIO(urlopen(search_items[z].get('link')).read()))
        # im.save(r'cache/d1.jpg')
        # self.img_7.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(1200))
        # z += 1
        # im = Image.open(io.BytesIO(urlopen(search_items[z].get('link')).read()))
        # im.save(r'cache/d1.jpg')
        # self.img_8.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(1200))
        # z += 1
        # im = Image.open(io.BytesIO(urlopen(search_items[z].get('link')).read()))
        # im.save(r'cache/d1.jpg')
        # self.img_9.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(1200))
        # z += 1
        # im = Image.open(io.BytesIO(urlopen(search_items[z].get('link')).read()))
        # im.save(r'cache/d1.jpg')
        # self.img_10.setPixmap(QPixmap(r'cache/d1.jpg').scaledToWidth(1200))
        # z += 1


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
